"""removed_game_id_from_achievements_users

Revision ID: 5b82289ab0db
Revises: 68e210d9fab1
Create Date: 2017-06-23 17:01:47.222880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b82289ab0db'
down_revision = '68e210d9fab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('achievements_users_ibfk_2', 'achievements_users', type_='foreignkey')
    op.drop_column('achievements_users', 'game_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements_users', sa.Column('game_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('achievements_users_ibfk_2', 'achievements_users', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###
