"""first

Revision ID: c9c6450137ad
Revises: 3f30b30cac63
Create Date: 2017-06-19 11:16:57.406815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c6450137ad'
down_revision = '3f30b30cac63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ranking', sa.Integer(), default=1, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ranking')
    # ### end Alembic commands ###
